GET http://localhost:3000/

###
GET http://localhost:3000/ping

###
GET http://localhost:3000/tecnologias

###
GET http://localhost:3000/tecnologias/destaques

###
GET http://localhost:3000/projetos

###
GET http://localhost:3000/projetos/3

### Testar redirecionamento para WhatsApp
GET http://localhost:4000/contato

